name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 假设您的主分支名为main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Build
      run: |
        mkdir build
        cd build
        emcmake cmake ..
        emmake make

    - name: Prepare deployment
      run: |
        mkdir deploy
        cp index.html deploy/
        cp build/wasm_multi_thread.* deploy/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy